# Basic docker compose
#   Used for e2e testing and development (integrated in DevContainer)

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: PASSWORD
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mail-server:
    image: mailhog/mailhog:v1.0.1
    ports:
      # Default ports: https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md
      - "127.0.0.1:1025:1025"
      - "8025:8025"

volumes:
  db_data: {}
