version: "3.8"

services:
  backend:
    image: backend
    depends_on:
      db:
        condition: service_healthy
        required: true
    environment:
      BE_DB_HOST: db
      BE_HTTP_PORT: 33000
    ports:
      - "33000:33000"

  frontend:
    image: frontend
    depends_on:
      - backend
    environment:
      PORT: 4200
    ports:
      - "34200:4200"

  office:
    image: office
    depends_on:
      - backend
    environment:
      PORT: 5200
    ports:
      - "35200:5200"
