version: "3.8"

services:
  backend:
    image: backend
    depends_on:
      db:
        condition: service_healthy
        required: true
    environment:
      BE_DB_HOST: db
      BE_HTTP_PORT: 33000
    ports:
      - "33000:33000"
