# This docker-compose is used in the CI for E2E testing
# The docker images should be build before using this compose `npm run docker:e2e`
#   Also, this indirectly tests the docker images

services:
  db:
    environment:
      POSTGRES_DB: e2e

  backend:
    image: backend
    depends_on:
      db:
        condition: service_healthy
        required: true
      mail-server:
        condition: service_started
        required: true
    environment:
      BE_DB_HOST: db
      BE_DB_TEST_NAME: e2e
      BE_HTTP_PORT: 33000
      BE_MAIL_HOST: mail-server
    ports:
      - "33000:33000"

  frontend:
    image: frontend
    depends_on:
      - backend
    environment:
      PORT: 34200
    ports:
      - "34200:34200"

  office:
    image: office
    depends_on:
      - backend
    environment:
      PORT: 35200
    ports:
      - "35200:35200"
