version: "3.4"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "nna"
      POSTGRES_USER: "nna"
      POSTGRES_PASSWORD: LOCAL_PASSWORD
    ports:
      - "127.0.0.1:5432:5432"
