name: CI

on:
  pull_request:
    branches:
      - master
      - release/v*
    types: [opened, synchronize, ready_for_review]

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  checks:
    if: github.event.pull_request.draft == false

    uses: ./.github/workflows/reusable-ci.yml
    secrets:
      NX_TOKEN: ${{ secrets.NX_WRITE_TOKEN }}
    with:
      # NX token not used to limit its usage (credits)
      NX_NO_CLOUD: ${{ contains(github.event.pull_request.labels.*.name, 'renovate') }}
