name: Release & Publish

on:
  push:
    branches:
      - master

jobs:
  job:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_WRITE_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 20.x

      - name: Install packages
        run: npm ci

      - name: Generate code coverage summary
        run: npm run test:ci
        # TODO: badges
# TODO: the remaining steps when more complete
