name: Release & Publish

on:
  push:
    branches:
      - master

jobs:
  job:
    # Ignore the heap-code bot commits and devDependencies
    if: ${{ github.actor != vars.HC_BOT && !(github.actor == 'renovate[bot]' && contains(github.event.head_commit.message, 'chore(deps):')) }}

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.HC_TOKEN }}
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_WRITE_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 20.x

      - name: Install packages
        run: npm ci

      - name: Generate code coverage summary
        run: npm run test:ci

      - name: Generate code coverage badges
        run: for path in ./dist/coverage/*/*; do npx node-jest-badges -c "$path/coverage-summary.json" -o ".badges/${path:16}/code/"; done

      - name: Set default code coverage badges
        run: for path in .badges/*/*/code; do cp $path/coverage-jest\ coverage.svg $path/coverage.svg; done

      - name: Add badges
        run: git add .badges

      # TODO
	  # - name: Release and publish
      #   run: npx release-it --ci

